executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: model
    json_schema:
      ui:options:
        title: Model
      ui:widget: self::model
    value:
      model: oomol-chat
      temperature: 0
      top_p: 0.5
      max_tokens: 4096
outputs_def:
  []
title: LLM
additional_inputs: true
additional_outputs: true
additional_outputs_def:
  - handle: output
    json_schema:
      type: string
additional_inputs_def:
  - handle: input
    json_schema:
      type: string
