executor:
  name: python
  options:
    entry: __init__.py
description: "%this-block-communicates-with-ai-language-models-to-generate-inte%"
inputs_def:
  - handle: messages
    description: "%conversation-history-in-message-format-system-user-assistant-rol%"
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          role:
            enum:
              - system
              - user
              - assistant
            ui:options:
              labels:
                - System
                - User
                - Assistant
          content:
            type: string
    value:
    nullable: true
  - group: Connection
    collapsed: true
  - handle: timeout
    description: "%maximum-time-in-seconds-to-wait-for-ai-response%"
    json_schema:
      type: number
      minimum: 0
    value: 30
  - handle: retry_times
    description: "%number-of-automatic-retry-attempts-on-connection-failure%"
    json_schema:
      type: integer
      minimum: 0
    value: 0
  - handle: retry_sleep
    description: "%delay-in-seconds-between-retry-attempts%"
    json_schema:
      type: number
      minimum: 0
    value: 3.5
  - handle: model
    description: "%ai-model-configuration-including-model-name-temperature-and-toke%"
    json_schema:
      ui:options:
        title: Model
        tags:
          - text
        excludeTags:
          - thinking
      ui:widget: self::model
    value:
      model: deepseek-chat
      temperature: 0.5
      top_p: 1
      max_tokens: 8192
  - handle: template
    description: "%prompt-template-that-defines-how-ai-should-respond-supports-vari%"
    json_schema:
      anyOf:
        - type: string
        - type: array
          items:
            type: object
            additionalProperties: false
            properties:
              role:
                enum:
                  - system
                  - user
                  - assistant
                ui:options:
                  labels:
                    - System
                    - User
                    - Assistant
              content:
                type: string
      ui:options:
        title: Prompt
      ui:widget: self::messages
    value:
      - role: user
        content: "{{input}}"
    schema_overrides:
      - schema:
          type: array
  - handle: skills
    description: "%additional-capabilities-or-tools-the-ai-can-use-during-response%"
    json_schema:
      type: array
      ui:options:
        title: Skills
      ui:widget: self::skills
    value:
      []
    schema_overrides:
      - schema:
          type: array
  - handle: stream
    description: "%enable-real-time-streaming-of-ai-responses-as-they-are-generated%"
    json_schema:
      type: boolean
    value: true
outputs_def:
  []
title: "%llm%"
additional_inputs: true
additional_outputs: true
additional_outputs_def:
  - handle: output
    description: AI-generated response text
    json_schema:
      type: string
additional_inputs_def:
  - handle: input
    description: Input text or data to be processed by the AI
    json_schema:
      type: string
      ui:widget: text
    value: hello!
