executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: messages
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          role:
            enum:
              - system
              - user
              - assistant
            ui:options:
              labels:
                - System
                - User
                - Assistant
          content:
            type: string
    value:
    nullable: true
  - group: Connection
    collapsed: true
  - handle: timeout
    json_schema:
      type: number
      minimum: 0
    value: 30
  - handle: retry_times
    json_schema:
      type: integer
      minimum: 0
    value: 0
  - handle: model
    json_schema:
      ui:options:
        title: Model
      ui:widget: self::model
    value:
      model: deepseek-chat
      temperature: 0.5
      top_p: 1
      max_tokens: 8192
  - handle: template
    json_schema:
      anyOf:
        - type: string
        - type: array
          items:
            type: object
            additionalProperties: false
            properties:
              role:
                enum:
                  - system
                  - user
                  - assistant
                ui:options:
                  labels:
                    - System
                    - User
                    - Assistant
              content:
                type: string
      ui:options:
        title: Prompt
      ui:widget: self::messages
    value:
      - role: user
        content: "{{input}}"
    schema_overrides:
      - schema:
          type: array
  - handle: retry_sleep
    json_schema:
      type: number
      minimum: 0
    value: 3.5
  - handle: skills
    json_schema:
      type: array
      ui:options:
        title: Skills
      ui:widget: self::skills
    value:
      []
    schema_overrides:
      - schema:
          type: array
  - handle: stream
    json_schema:
      type: boolean
    value: true
outputs_def:
  - handle: output
    json_schema:
      type: string
title: LLM chat
additional_inputs: true
additional_outputs: false
additional_inputs_def:
  - handle: input
    json_schema:
      type: string
      ui:widget: text
    value: hello!
