export const mockModels = [
  {
    "model_name": "FunAudioLLM/CosyVoice2-0.5B",
    "model_display_name": "FunAudioLLM/CosyVoice2-0.5B",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 4096,
    "tags": [],
    "channel_name": "SiliconFlow",
    "map_model": "",
    "ratio": 7,
    "input_ratio": 7,
    "output_ratio": 7
  },
  {
    "model_name": "Moonshot-Kimi-K2-Instruct",
    "model_display_name": "Moonshot-Kimi-K2-Instruct",
    "temperature": 0.3,
    "top_p": 1,
    "max_tokens": 131072,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.7,
    "input_ratio": 0.7,
    "output_ratio": 2.8
  },
  {
    "model_name": "Qwen/QwQ-32B",
    "model_display_name": "Qwen/QwQ-32B",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 4096,
    "tags": [],
    "channel_name": "SiliconFlow",
    "map_model": "",
    "ratio": 1,
    "input_ratio": 1,
    "output_ratio": 1
  },
  {
    "model_name": "anthropic/claude-3.7-sonnet",
    "model_display_name": "anthropic/claude-3.7-sonnet",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 3.8,
    "input_ratio": 3.8,
    "output_ratio": 19
  },
  {
    "model_name": "anthropic/claude-sonnet-4",
    "model_display_name": "anthropic/claude-sonnet-4",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 3.8,
    "input_ratio": 3.8,
    "output_ratio": 19
  },
  {
    "model_name": "deepseek-chat",
    "model_display_name": "",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [
      "Text"
    ],
    "channel_name": "DeepSeek",
    "map_model": "",
    "ratio": 0.38,
    "input_ratio": 0.38,
    "output_ratio": 1.52
  },
  {
    "model_name": "deepseek-r1-0528",
    "model_display_name": "deepseek-r1-0528",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 65536,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.75,
    "input_ratio": 0.75,
    "output_ratio": 3
  },
  {
    "model_name": "deepseek-r1-250528",
    "model_display_name": "deepseek-r1-250528",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 65536,
    "tags": [],
    "channel_name": "VolcEngine",
    "map_model": "",
    "ratio": 0.75,
    "input_ratio": 0.75,
    "output_ratio": 3
  },
  {
    "model_name": "deepseek-reasoner",
    "model_display_name": "",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 65536,
    "tags": [],
    "channel_name": "DeepSeek",
    "map_model": "",
    "ratio": 0.75,
    "input_ratio": 0.75,
    "output_ratio": 3
  },
  {
    "model_name": "deepseek-v3",
    "model_display_name": "deepseek-v3",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.38,
    "input_ratio": 0.38,
    "output_ratio": 1.52
  },
  {
    "model_name": "deepseek-v3-250324",
    "model_display_name": "deepseek-v3-250324",
    "temperature": 0.1,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "VolcEngine",
    "map_model": "",
    "ratio": 0.38,
    "input_ratio": 0.38,
    "output_ratio": 1.52
  },
  {
    "model_name": "doubao-1-5-pro-32k-250115",
    "model_display_name": "",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [
      "32k"
    ],
    "channel_name": "VolcEngine",
    "map_model": "",
    "ratio": 0.2,
    "input_ratio": 0.2,
    "output_ratio": 0.8
  },
  {
    "model_name": "doubao-seedream-3-0-t2i-250415",
    "model_display_name": "doubao-seedream-3-0-t2i-250415",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 4096,
    "tags": [],
    "channel_name": "VolcEngine",
    "map_model": "",
    "ratio": 1,
    "input_ratio": 1,
    "output_ratio": 1
  },
  {
    "model_name": "gemini2.5-flash",
    "model_display_name": "google/gemini-2.5-flash-preview",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "google/gemini-2.5-flash-preview",
    "ratio": 0.2,
    "input_ratio": 0.2,
    "output_ratio": 0.8
  },
  {
    "model_name": "google/gemini-2.5-pro-preview",
    "model_display_name": "google/gemini-2.5-pro-preview",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 2.5,
    "input_ratio": 2.5,
    "output_ratio": 15
  },
  {
    "model_name": "kimi-k2-0711-preview",
    "model_display_name": "kimi-k2-0711-preview",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 131072,
    "tags": [],
    "channel_name": "Kimi",
    "map_model": "",
    "ratio": 0.7,
    "input_ratio": 0.7,
    "output_ratio": 2.8
  },
  {
    "model_name": "mistralai/mistral-medium-3",
    "model_display_name": "mistralai/mistral-medium-3",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 0.5,
    "input_ratio": 0.5,
    "output_ratio": 1
  },
  {
    "model_name": "moonshotai/kimi-k2",
    "model_display_name": "moonshotai/kimi-k2",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 134144,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 0.7,
    "input_ratio": 0.7,
    "output_ratio": 2.8
  },
  {
    "model_name": "oomol-VL",
    "model_display_name": "qwen2.5-vl-7b-instruct",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "qwen2.5-vl-7b-instruct",
    "ratio": 0.38,
    "input_ratio": 0.38,
    "output_ratio": 1.52
  },
  {
    "model_name": "oomol-chat",
    "model_display_name": "",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [
      "Text"
    ],
    "channel_name": "DeepSeek",
    "map_model": "deepseek-chat",
    "ratio": 0.38,
    "input_ratio": 0.38,
    "output_ratio": 1.52
  },
  {
    "model_name": "openai/gpt-4.1",
    "model_display_name": "openai/gpt-4.1",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 33792,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 2,
    "input_ratio": 2,
    "output_ratio": 8
  },
  {
    "model_name": "openai/gpt-4.1-mini",
    "model_display_name": "openai/gpt-4.1-mini",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 0.5,
    "input_ratio": 0.5,
    "output_ratio": 2
  },
  {
    "model_name": "openai/gpt-4o-mini",
    "model_display_name": "openai/gpt-4o-mini",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 0.2,
    "input_ratio": 0.2,
    "output_ratio": 0.8
  },
  {
    "model_name": "qwen-max-0125",
    "model_display_name": "",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [
      "Text",
      "Function Call"
    ],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.5,
    "input_ratio": 0.5,
    "output_ratio": 2
  },
  {
    "model_name": "qwen-plus",
    "model_display_name": "qwen-plus",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.2,
    "input_ratio": 0.2,
    "output_ratio": 0.8
  },
  {
    "model_name": "qwen2.5-vl-7b-instruct",
    "model_display_name": "qwen2.5-vl-7b-instruct",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.38,
    "input_ratio": 0.38,
    "output_ratio": 1.52
  },
  {
    "model_name": "qwen3-235b-a22b",
    "model_display_name": "qwen3-235b-a22b",
    "temperature": 0.2,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.8,
    "input_ratio": 0.8,
    "output_ratio": 2.4
  },
  {
    "model_name": "qwen3-coder-480b-a35b-instruct",
    "model_display_name": "qwen3-coder-480b-a35b-instruct",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 65536,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 1.2,
    "input_ratio": 1.2,
    "output_ratio": 4.8
  },
  {
    "model_name": "qwen3-coder-plus",
    "model_display_name": "qwen3-coder-plus",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 65536,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 1.5,
    "input_ratio": 1.5,
    "output_ratio": 6
  },
  {
    "model_name": "qwq-plus",
    "model_display_name": "qwq-plus",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "AlibabaCloud",
    "map_model": "",
    "ratio": 0.3,
    "input_ratio": 0.3,
    "output_ratio": 0.9
  },
  {
    "model_name": "x-ai/grok-3-beta",
    "model_display_name": "x-ai/grok-3-beta",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 5.6,
    "input_ratio": 5.6,
    "output_ratio": 28
  },
  {
    "model_name": "x-ai/grok-3-mini-beta",
    "model_display_name": "x-ai/grok-3-mini-beta",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 8192,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 0.5,
    "input_ratio": 0.5,
    "output_ratio": 2.5
  },
  {
    "model_name": "x-ai/grok-4",
    "model_display_name": "x-ai/grok-4",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 262144,
    "tags": [],
    "channel_name": "OpenRouter",
    "map_model": "",
    "ratio": 4,
    "input_ratio": 4,
    "output_ratio": 20
  }
]
